package javastandard;

public class TryCatch {

    /*
    * try {
    <수행할 문장 1>;
    <수행할 문장 2>;
    ...
} catch(예외1) {
    <수행할 문장 A>;
    ...
} catch(예외2) {
    <수행할 문장 a>;
    ...
}
tny 문 안의 수행할 문장 중에서 예외가 발생하지 않는다면 catch 문에 속한 문잗들은 수행되지 않는다.
하지만 try 문 안의 문장을 수행하는 도중에 예외가 발생하면 예외에 해당되는 catch문이 수행된다.
 */
}
